package com.webjetcms.ai;

import java.util.Arrays;
import java.util.Objects;

/**
 * Binary content generated by an AI provider.
 *
 * @param data generated bytes; the record stores and returns defensive copies
 * @param mediaType MIME type, defaulting to {@code application/octet-stream} when blank
 */
public record GeneratedMedia(byte[] data, String mediaType) {

    /**
     * Creates generated media while normalizing its data and media type.
     *
     * @param data generated bytes, or {@code null} for an empty payload
     * @param mediaType MIME type, or a null/blank value for the binary default
     */
    public GeneratedMedia {
        data = data == null ? new byte[0] : Arrays.copyOf(data, data.length);
        mediaType = mediaType == null || mediaType.isBlank() ? "application/octet-stream" : mediaType;
    }

    /**
     * Returns a defensive copy of the generated bytes.
     *
     * @return a newly allocated byte array
     */
    @Override
    public byte[] data() {
        return Arrays.copyOf(data, data.length);
    }

    /** Uses byte content, rather than array identity, for value equality. */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GeneratedMedia that
            && Arrays.equals(data, that.data)
            && Objects.equals(mediaType, that.mediaType);
    }

    /** Uses byte content, rather than array identity, for the value hash. */
    @Override
    public int hashCode() {
        return 31 * Arrays.hashCode(data) + Objects.hashCode(mediaType);
    }
}
